name: project-lint

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.12.0
        with:
          # Specify the PHP version
          php-version: '7.4'
      - name: Install
        # Install project
        run: make install
      - name: Run linter
        # Run Linter
        run: make lint